language: nodejs
node_js:
  - "stable"
before_install:
  - node --version
  - npm --version
  - cd Server\ Backend/
install:
  - npm install
cache:
  directories:
    - Server\ Backend/node_modules
script:
  - npm run test
notifications:
  webhooks:
    - https://discordapp.com/api/webhooks/415299843217555467/6GiUJHlEdTQUyMLKSF6AmxB6fpGfQc9eNtLkn3AGVaAdGZLTf0YZVpedpoIFMEQNEt75