matrix:
  include:

    - language: nodejs
      node_js:
        - "stable"
      before_install:
        - node --version
        - npm --version
        - cd Server\ Backend/
      install:
        - npm install
      cache:
        directories:
          - Server\ Backend/node_modules
      script:
        - npm run test

    - language: java
      jdk: oraclejdk8
      before_script:
        - cd Database/Dictionary
      cache:
        directories:
        - $HOME/.m2
        
    - language: java
      jdk: oraclejdk8
      before_script:
        - cd Database/GameDB
      cache:
        directories:
        - $HOME/.m2
