cd "C:\Users\Gage\Documents\GitHub\Red-Team\Database\Dictionary"
start powershell /c "mvn spring-boot:run; pause"
cd "C:\Users\Gage\Documents\GitHub\Red-Team\Database\GameDB"
start powershell /c "mvn spring-boot:run; pause"
cd "C:\Users\Gage\Documents\GitHub\Red-Team\Server Backend"
start powershell /c "npm run start; pause"
cd "C:\Users\Gage\Documents\GitHub\Red-Team\Stats Backend"
start powershell /c "npm run start; pause"